var EBOOKS = {
  'ebook-30day-handstand': {
    name: '30-Day Handstand Challenge',
    price: 29.99,
    category: 'challenge',
    topic: 'handstand',
    emoji: '🤸',
    badge: 'Challenge',
    badgeColor: '#e84393',
    tagline: 'A full month of daily handstand training.',
    desc: 'Build a consistent handstand practice in 30 days. Each session is structured and progressive — starting with wrist prep, hollow body work, and wall holds, then moving into freestanding balance and control. No equipment needed, no gym required.',
    duration: '30 days',
    videos: '30 videos',
    session: '20–40 min/day',
    includes: [
      '30 daily video sessions',
      'Progressive wrist & shoulder prep',
      'Wall drills to freestanding progressions',
      'Balance and control techniques',
      'Rest day mobility work included'
    ]
  },
  'ebook-calisthenics-series': {
    name: 'Calisthenics Follow-Along Series',
    price: 24.99,
    category: 'followalong',
    topic: 'calisthenics',
    emoji: '💪',
    badge: 'Follow-Along',
    badgeColor: '#2e86de',
    tagline: 'Train alongside me in real time.',
    desc: 'Upper body, core, and full-body sessions you can do anywhere — bodyweight only. Press play and work alongside me. No planning, no second-guessing, just show up and train. Perfect for anyone who wants structure without a gym.',
    duration: '8 weeks',
    videos: '24 videos',
    session: '30–50 min/session',
    includes: [
      '24 full follow-along sessions',
      'Upper body, core & full-body splits',
      'Progressions for all levels',
      'Bodyweight only — no equipment',
      'Warm-up and cool-down included'
    ]
  },
  'ebook-mobility-program': {
    name: 'Wrist & Shoulder Mobility Program',
    price: 19.99,
    category: 'guide',
    topic: 'mobility',
    emoji: '🧘',
    badge: 'Guide',
    badgeColor: '#27ae60',
    tagline: 'The foundation most people skip.',
    desc: 'Wrist and shoulder mobility is the most neglected part of handstand and calisthenics training. This program addresses the root causes of wrist pain, shoulder impingement, and poor overhead range — so you can train harder without breaking down.',
    duration: '4 weeks',
    videos: '12 videos',
    session: '15–25 min/session',
    includes: [
      '12 structured mobility sessions',
      'Wrist strengthening & prep protocols',
      'Shoulder joint health & range work',
      'Thoracic spine mobility exercises',
      'Daily maintenance routines'
    ]
  },
  'sm-hs-beginner-fa': {
    name: 'Beginner Handstand Follow-Along',
    price: 14.99,
    category: 'followalong',
    topic: 'handstand',
    emoji: '🤸',
    badge: 'Follow-Along',
    badgeColor: '#2e86de',
    tagline: 'Your first steps toward a freestanding handstand.',
    desc: 'Never trained handstands before? This is where you start. We build everything from scratch — hand placement, wrist loading, hollow body tension, and your first wall holds. Follow along and stop guessing.',
    duration: '3 weeks',
    videos: '12 videos',
    session: '15–25 min/session',
    includes: [
      '12 beginner-focused sessions',
      'Wrist prep and hand placement basics',
      'Hollow body and core tension work',
      'First wall handstand progressions',
      'No prior handstand experience needed'
    ]
  },
  'sm-mobility-30d': {
    name: '30-Day Mobility Challenge',
    price: 19.99,
    category: 'challenge',
    topic: 'mobility',
    emoji: '🧘',
    badge: 'Challenge',
    badgeColor: '#e84393',
    tagline: 'One month to move better.',
    desc: 'A daily mobility challenge covering hips, hamstrings, spine, and shoulders. Short sessions you can do every day — even on rest days. By the end of 30 days you\'ll notice the difference in every movement you do.',
    duration: '30 days',
    videos: '30 videos',
    session: '10–20 min/day',
    includes: [
      '30 daily mobility sessions',
      'Hip flexor & hamstring focus',
      'Shoulder & thoracic work',
      'Spinal mobility and decompression',
      'Works as a standalone or alongside any training'
    ]
  },
  'sm-pike-compression': {
    name: 'Pike & Compression Training',
    price: 17.99,
    category: 'guide',
    topic: 'handstand',
    emoji: '📐',
    badge: 'Guide',
    badgeColor: '#27ae60',
    tagline: 'Build the compression strength handstands demand.',
    desc: 'Pike flexibility and active compression are key to controlling a handstand at the top. This guide targets exactly that — building the active flexibility and hip flexor strength to shape your handstand and eventually press to it.',
    duration: '4 weeks',
    videos: '10 videos',
    session: '20–30 min/session',
    includes: [
      '10 focused training sessions',
      'Active pike and pancake work',
      'Hip flexor strengthening exercises',
      'Press handstand entry prep',
      'Seated and standing compression drills'
    ]
  },
  'sm-lsit-vsit': {
    name: 'L-Sit to V-Sit Program',
    price: 22.99,
    category: 'challenge',
    topic: 'calisthenics',
    emoji: '⚡',
    badge: 'Challenge',
    badgeColor: '#e84393',
    tagline: 'From tucked hold to full V-sit.',
    desc: 'The L-sit is a fundamental skill most people stay stuck on for too long. This program breaks down every progression — from tuck L-sit to straight leg L-sit, all the way to V-sit — with clear drills and weekly structure.',
    duration: '6 weeks',
    videos: '14 videos',
    session: '20–35 min/session',
    includes: [
      '14 structured sessions',
      'Tuck → L-sit → V-sit progressions',
      'Floor, parallette, and bar variations',
      'Hip flexor and core conditioning',
      'Testing benchmarks each week'
    ]
  },
  'sm-shoulder-warmup': {
    name: 'Shoulder Warm-Up Series',
    price: 12.99,
    category: 'guide',
    topic: 'mobility',
    emoji: '🙆',
    badge: 'Guide',
    badgeColor: '#27ae60',
    tagline: 'The warm-up you should be doing before every session.',
    desc: 'A short, effective shoulder warm-up routine designed for handstand and overhead training. Use it before every session to protect your joints, increase range, and actually feel ready to train.',
    duration: 'Ongoing',
    videos: '6 videos',
    session: '8–12 min/session',
    includes: [
      '6 shoulder prep routines',
      'Internal & external rotation work',
      'Banded and bodyweight variations',
      'Pre-handstand activation sequence',
      'Quick version for time-limited sessions'
    ]
  },
  'sm-hspu': {
    name: 'Handstand Push-Up Program',
    price: 24.99,
    category: 'challenge',
    topic: 'handstand',
    emoji: '🔥',
    badge: 'Challenge',
    badgeColor: '#e84393',
    tagline: 'Build pressing strength from the ground up.',
    desc: 'The handstand push-up is one of the most impressive bodyweight feats. This program builds the overhead pressing strength, shoulder stability, and handstand control to get you there — with wall-supported progressions to full freestanding reps.',
    duration: '8 weeks',
    videos: '18 videos',
    session: '25–40 min/session',
    includes: [
      '18 progressive sessions',
      'Overhead strength & shoulder stability',
      'Wall-supported HSPU progressions',
      'Neck and head positioning guidance',
      'Strength benchmarks throughout'
    ]
  },
  'sm-flexibility': {
    name: 'Full Body Flexibility Guide',
    price: 19.99,
    category: 'guide',
    topic: 'mobility',
    emoji: '🦵',
    badge: 'Guide',
    badgeColor: '#27ae60',
    tagline: 'Systematic flexibility for the whole body.',
    desc: 'A complete, head-to-toe flexibility program covering every major area — ankles, hips, hamstrings, spine, and shoulders. Works on its own or as a mobility complement to any training style.',
    duration: '6 weeks',
    videos: '14 videos',
    session: '20–30 min/session',
    includes: [
      '14 full-body mobility sessions',
      'Ankle, hip, and hamstring flexibility',
      'Spinal and thoracic mobility',
      'Shoulder and chest opening',
      'Passive and active stretching techniques'
    ]
  },
  'sm-rings': {
    name: 'Ring Training Basics',
    price: 22.99,
    category: 'followalong',
    topic: 'calisthenics',
    emoji: '💍',
    badge: 'Follow-Along',
    badgeColor: '#2e86de',
    tagline: 'Start training rings the right way.',
    desc: 'Gymnastic rings are one of the best training tools for upper body strength and stability. This follow-along series teaches the fundamentals — support position, ring rows, dips, and basic pushing and pulling patterns.',
    duration: '5 weeks',
    videos: '15 videos',
    session: '25–40 min/session',
    includes: [
      '15 ring-focused sessions',
      'Ring support and stability basics',
      'Ring rows, dips, and push variations',
      'Transition and coordination drills',
      'Progressive difficulty each week'
    ]
  },
  'sm-morning-mobility': {
    name: 'Morning Mobility Routine',
    price: 14.99,
    category: 'followalong',
    topic: 'beginner',
    emoji: '🌅',
    badge: 'Follow-Along',
    badgeColor: '#2e86de',
    tagline: 'The best way to start your day.',
    desc: 'A short morning routine you can do before your day starts. Loosens the joints, activates the muscles you need, and sets the tone for the rest of the day. Beginner-friendly and equipment-free.',
    duration: 'Ongoing',
    videos: '8 videos',
    session: '10–15 min/session',
    includes: [
      '8 follow-along morning sessions',
      'Joint mobilisation sequence',
      'Light activation work',
      'Breathing and nervous system reset',
      'Beginner-friendly — no experience needed'
    ]
  },
  'sm-core': {
    name: 'Core Strength Series',
    price: 19.99,
    category: 'followalong',
    topic: 'calisthenics',
    emoji: '🏋️',
    badge: 'Follow-Along',
    badgeColor: '#2e86de',
    tagline: 'Build core strength that actually transfers.',
    desc: 'Not crunches. Real core training — hollow body, plank progressions, anti-rotation work, and dynamic control. The kind of core strength that makes every other skill stronger.',
    duration: '6 weeks',
    videos: '16 videos',
    session: '20–30 min/session',
    includes: [
      '16 progressive core sessions',
      'Hollow body and arch body mastery',
      'Plank and anti-rotation work',
      'Dynamic core for movement skills',
      'Handstand and skill carryover focus'
    ]
  },
  'sm-beginner-cal': {
    name: 'Beginner Calisthenics',
    price: 17.99,
    category: 'followalong',
    topic: 'beginner',
    emoji: '🌱',
    badge: 'Follow-Along',
    badgeColor: '#2e86de',
    tagline: 'Start strong. Build the right way.',
    desc: 'If you\'re new to bodyweight training, this is your starting point. Learn the foundational push, pull, squat, and hinge movements with proper form — so you build strength without developing bad habits.',
    duration: '6 weeks',
    videos: '18 videos',
    session: '25–35 min/session',
    includes: [
      '18 beginner-level sessions',
      'Push-up, row, squat & hinge foundations',
      'Form coaching cues throughout',
      'Progressive weekly structure',
      'No equipment needed'
    ]
  },
  'sm-pancake': {
    name: 'Straddle & Pancake Program',
    price: 19.99,
    category: 'guide',
    topic: 'mobility',
    emoji: '🥞',
    badge: 'Guide',
    badgeColor: '#27ae60',
    tagline: 'Open your hips and hit the floor.',
    desc: 'The pancake and straddle are key positions for handstand presses, gymnastics, and general mobility. This program systematically builds the hip and hamstring flexibility you need to get your chest to the floor in a straddle.',
    duration: '6 weeks',
    videos: '12 videos',
    session: '20–30 min/session',
    includes: [
      '12 targeted flexibility sessions',
      'Straddle and pancake progressions',
      'Hip external rotation work',
      'Inner thigh and groin stretching',
      'Active vs passive flexibility training'
    ]
  },
  'sm-oahs': {
    name: 'One Arm Handstand Intro',
    price: 27.99,
    category: 'guide',
    topic: 'handstand',
    emoji: '☝️',
    badge: 'Guide',
    badgeColor: '#27ae60',
    tagline: 'The path to a one-arm handstand starts here.',
    desc: 'The one-arm handstand is an elite skill — but the preparation for it starts earlier than most people think. This guide introduces the shift work, finger pressure, side balance, and structural prerequisites to begin your OAH journey.',
    duration: '8 weeks',
    videos: '16 videos',
    session: '30–45 min/session',
    includes: [
      '16 advanced handstand sessions',
      'Weight shifting and side balance drills',
      'Finger and wrist pressure control',
      'Wall-supported one-arm progressions',
      'Prerequisites checklist before you begin'
    ]
  },
  'sm-planche': {
    name: 'Planche Fundamentals',
    price: 24.99,
    category: 'challenge',
    topic: 'calisthenics',
    emoji: '🛡️',
    badge: 'Challenge',
    badgeColor: '#e84393',
    tagline: 'Build the base for a planche.',
    desc: 'The planche is one of the hardest bodyweight skills. This program builds everything you need to start working toward it — straight arm strength, protraction, lean, and tuck planche holds — with a structured weekly challenge format.',
    duration: '8 weeks',
    videos: '20 videos',
    session: '30–45 min/session',
    includes: [
      '20 structured sessions',
      'Straight arm strength conditioning',
      'Scapular protraction and depression work',
      'Lean and tuck planche progressions',
      'Weekly strength benchmarks'
    ]
  },
  'sm-hip-hamstring': {
    name: 'Hip Flexor & Hamstring Series',
    price: 14.99,
    category: 'guide',
    topic: 'mobility',
    emoji: '🦴',
    badge: 'Guide',
    badgeColor: '#27ae60',
    tagline: 'Fix the two tightest areas in most athletes.',
    desc: 'Tight hip flexors and hamstrings limit everything — your squat, your deadlift, your handstand, your splits. This series directly targets both areas with a combination of passive stretching and active flexibility work.',
    duration: '4 weeks',
    videos: '10 videos',
    session: '15–20 min/session',
    includes: [
      '10 focused sessions',
      'Hip flexor lengthening and activation',
      'Hamstring passive and active stretching',
      'PNF and loaded flexibility techniques',
      'Can be added to any training programme'
    ]
  },
  'sm-hs-alignment': {
    name: 'Handstand Line & Alignment',
    price: 19.99,
    category: 'guide',
    topic: 'handstand',
    emoji: '📏',
    badge: 'Guide',
    badgeColor: '#27ae60',
    tagline: 'Fix what\'s actually wrong with your handstand.',
    desc: 'Most people who can kick up into a handstand still have major alignment issues — banana back, bent elbows, misaligned hips. This guide diagnoses and corrects the most common form errors with targeted drills.',
    duration: '4 weeks',
    videos: '12 videos',
    session: '20–30 min/session',
    includes: [
      '12 technique-focused sessions',
      'Common alignment error breakdowns',
      'Hollow body integration drills',
      'Hip stacking and shoulder positioning',
      'Video self-analysis checklist'
    ]
  },
  'sm-pushup': {
    name: 'Push-Up Mastery',
    price: 17.99,
    category: 'followalong',
    topic: 'beginner',
    emoji: '👊',
    badge: 'Follow-Along',
    badgeColor: '#2e86de',
    tagline: 'Master the most underrated exercise.',
    desc: 'Most people do push-ups wrong. This follow-along series teaches perfect push-up form, then progressively builds strength through variations — wide, narrow, archer, ring push-ups and beyond.',
    duration: '5 weeks',
    videos: '12 videos',
    session: '15–25 min/session',
    includes: [
      '12 push-up focused sessions',
      'Form correction and body positioning',
      'Wide, narrow, and archer variations',
      'Ring push-up introduction',
      'Progressive overload built in'
    ]
  },
  'sm-balance': {
    name: 'Balance Training Series',
    price: 22.99,
    category: 'followalong',
    topic: 'handstand',
    emoji: '⚖️',
    badge: 'Follow-Along',
    badgeColor: '#2e86de',
    tagline: 'Train the thing that actually makes a handstand.',
    desc: 'Balance is a skill you can train directly. This series isolates balance work — finger pressure, micro-adjustments, wrist movements, and endurance — so your handstand stops being a lottery and becomes something you can control.',
    duration: '5 weeks',
    videos: '14 videos',
    session: '20–30 min/session',
    includes: [
      '14 balance-specific sessions',
      'Finger pressure and wrist control drills',
      'Kick-up consistency training',
      'Hold duration and endurance work',
      'Wall and freestanding progressions'
    ]
  },
  'sm-core-30d': {
    name: '30-Day Core Challenge',
    price: 19.99,
    category: 'challenge',
    topic: 'calisthenics',
    emoji: '💥',
    badge: 'Challenge',
    badgeColor: '#e84393',
    tagline: 'Thirty days of real core work.',
    desc: 'A daily core challenge that goes beyond sit-ups. Each session targets a different aspect of core strength — anti-rotation, flexion, extension, and dynamic control — building serious functional strength over 30 days.',
    duration: '30 days',
    videos: '30 videos',
    session: '10–20 min/day',
    includes: [
      '30 daily core sessions',
      'Anti-rotation and stability work',
      'Hollow body and L-sit conditioning',
      'Dragon flag and advanced progressions',
      'Rest day mobility included'
    ]
  },
  'sm-fullbody-fa': {
    name: 'Full Body Follow-Along',
    price: 24.99,
    category: 'followalong',
    topic: 'calisthenics',
    emoji: '🌀',
    badge: 'Follow-Along',
    badgeColor: '#2e86de',
    tagline: 'One session, full body, done.',
    desc: 'A complete full-body follow-along programme. Each session hits push, pull, hinge, and core — all in one workout. No thinking required. Just press play and get through it.',
    duration: '8 weeks',
    videos: '24 videos',
    session: '35–50 min/session',
    includes: [
      '24 full-body sessions',
      'Push, pull, hinge, and core in every workout',
      'Bodyweight and optional weighted variations',
      'Progressive difficulty week by week',
      'Warm-up and cool-down included'
    ]
  }
};
