var SEARCH_INDEX = [
  // Pages
  { type: 'Page', title: 'Home', url: 'index.html', desc: 'Handstands, calisthenics & mobility coaching', keywords: 'home coaching ilai shimony' },
  { type: 'Page', title: 'Coaching', url: 'coaching.html', desc: '1-on-1 online coaching plans — Starter, Elite, Pro', keywords: 'coaching plans 1on1 personal program' },
  { type: 'Page', title: 'E-Books & Programs', url: 'ebooks.html', desc: 'Video library — follow-alongs, challenges, guides', keywords: 'ebooks programs video library buy' },
  { type: 'Page', title: 'My App', url: 'app.html', desc: 'The Elite Coaching Terminal — training app', keywords: 'app application training terminal' },
  { type: 'Page', title: 'Events & Workshops', url: 'events.html', desc: 'Live workshops and handstand intensives — coming soon', keywords: 'events workshops live group sessions' },
  { type: 'Page', title: 'About Me', url: 'about.html', desc: "Ilai's story — from beginner to coaching athletes worldwide", keywords: 'about story ilai shimony background' },
  { type: 'Page', title: 'FAQ', url: 'faq.html', desc: 'Frequently asked questions about coaching and programs', keywords: 'faq questions answers' },
  { type: 'Page', title: 'Apply for Coaching', url: 'apply.html', desc: 'Apply to work with Ilai — 1-on-1 coaching application', keywords: 'apply coaching application form' },
  // Services
  { type: 'Service', title: 'Video Analysis', url: 'product-video-analysis.html', desc: 'Send up to 10 videos, get detailed feedback — $14.99', keywords: 'video analysis feedback form technique review' },
  { type: 'Service', title: 'Coaching Call', url: 'product-coaching-call.html', desc: '1-on-1 video call session — $49.99', keywords: 'coaching call session video 1on1' },
  { type: 'Service', title: 'Video Sessions', url: 'product-video-sessions.html', desc: 'Live video training sessions', keywords: 'video sessions live training' },
  // Programs
  { type: 'Program', title: '30-Day Handstand Challenge', url: 'product-ebook.html?id=ebook-30day-handstand', desc: 'A full month of daily handstand training — $29.99', keywords: 'handstand challenge 30 day daily freestanding' },
  { type: 'Program', title: 'Calisthenics Follow-Along Series', url: 'product-ebook.html?id=ebook-calisthenics-series', desc: 'Train alongside me in real time — $24.99', keywords: 'calisthenics follow along bodyweight series' },
  { type: 'Program', title: 'Wrist & Shoulder Mobility Program', url: 'product-ebook.html?id=ebook-mobility-program', desc: 'Complete mobility for handstand training — $19.99', keywords: 'wrist shoulder mobility program guide' },
  { type: 'Program', title: 'Beginner Handstand Follow-Along', url: 'product-ebook.html?id=sm-hs-beginner-fa', desc: 'First steps toward a freestanding handstand — $14.99', keywords: 'beginner handstand follow along start' },
  { type: 'Program', title: '30-Day Mobility Challenge', url: 'product-ebook.html?id=sm-mobility-30d', desc: 'One month to move better — $19.99', keywords: 'mobility challenge 30 day hips flexibility' },
  { type: 'Program', title: 'Pike & Compression Training', url: 'product-ebook.html?id=sm-pike-compression', desc: 'Build compression strength for handstands — $17.99', keywords: 'pike compression handstand press flexibility' },
  { type: 'Program', title: 'L-Sit to V-Sit Program', url: 'product-ebook.html?id=sm-lsit-vsit', desc: 'From tucked hold to full V-sit — $22.99', keywords: 'lsit vsit core compression calisthenics' },
  { type: 'Program', title: 'Shoulder Warm-Up Series', url: 'product-ebook.html?id=sm-shoulder-warmup', desc: 'The warm-up for every session — $12.99', keywords: 'shoulder warmup prep handstand overhead' },
  { type: 'Program', title: 'Handstand Push-Up Program', url: 'product-ebook.html?id=sm-hspu', desc: 'Build pressing strength for HSPU — $24.99', keywords: 'handstand pushup hspu overhead press strength' },
  { type: 'Program', title: 'Full Body Flexibility Guide', url: 'product-ebook.html?id=sm-flexibility', desc: 'Head-to-toe flexibility program — $19.99', keywords: 'flexibility guide full body mobility' },
  { type: 'Program', title: 'Ring Training Basics', url: 'product-ebook.html?id=sm-rings', desc: 'Start training gymnastic rings — $22.99', keywords: 'rings ring training gymnastics basics' },
  { type: 'Program', title: 'Morning Mobility Routine', url: 'product-ebook.html?id=sm-morning-mobility', desc: 'The best way to start your day — $14.99', keywords: 'morning mobility routine beginner daily' },
  { type: 'Program', title: 'Core Strength Series', url: 'product-ebook.html?id=sm-core', desc: 'Real core training that transfers — $19.99', keywords: 'core strength hollow body plank series' },
  { type: 'Program', title: 'Beginner Calisthenics', url: 'product-ebook.html?id=sm-beginner-cal', desc: 'Start strong, build the right way — $17.99', keywords: 'beginner calisthenics bodyweight start pushup' },
  { type: 'Program', title: 'Straddle & Pancake Program', url: 'product-ebook.html?id=sm-pancake', desc: 'Open your hips and hit the floor — $19.99', keywords: 'straddle pancake flexibility splits hip' },
  { type: 'Program', title: 'One Arm Handstand Intro', url: 'product-ebook.html?id=sm-oahs', desc: 'Begin your OAH journey — $27.99', keywords: 'one arm handstand oahs advanced' },
  { type: 'Program', title: 'Planche Fundamentals', url: 'product-ebook.html?id=sm-planche', desc: 'Build the base for a planche — $24.99', keywords: 'planche fundamentals straight arm calisthenics' },
  { type: 'Program', title: 'Hip Flexor & Hamstring Series', url: 'product-ebook.html?id=sm-hip-hamstring', desc: 'Fix the two tightest areas — $14.99', keywords: 'hip flexor hamstring mobility flexibility' },
  { type: 'Program', title: 'Handstand Line & Alignment', url: 'product-ebook.html?id=sm-hs-alignment', desc: 'Fix your handstand form — $19.99', keywords: 'handstand alignment line form technique' },
  { type: 'Program', title: 'Push-Up Mastery', url: 'product-ebook.html?id=sm-pushup', desc: 'Master the most underrated exercise — $17.99', keywords: 'pushup push up mastery beginner form' },
  { type: 'Program', title: 'Balance Training Series', url: 'product-ebook.html?id=sm-balance', desc: 'Train the thing that makes a handstand — $22.99', keywords: 'balance training handstand control' },
  { type: 'Program', title: '30-Day Core Challenge', url: 'product-ebook.html?id=sm-core-30d', desc: 'Thirty days of real core work — $19.99', keywords: '30 day core challenge calisthenics' },
  { type: 'Program', title: 'Full Body Follow-Along', url: 'product-ebook.html?id=sm-fullbody-fa', desc: 'One session, full body, done — $24.99', keywords: 'full body follow along calisthenics' },
];
